#!/usr/bin/env bash

# Get the branch name without using 'basename'
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Set up tmux
session_name=$(tmux display-message -p "#S")
clean_name=$(echo "$branch_name" | tr "./" "__")
target="$session_name:$clean_name"

# Start tmux server if not already running
if [ -z "$(tmux list-sessions 2>/dev/null)" ]; then
  tmux new-session -d -s "$session_name"
fi

# Create a new window if it doesn't exist
if [ -z "$(tmux list-windows -t "$session_name" | grep "$clean_name")" ]; then
  tmux neww -dn "$clean_name"
fi

shift
tmux send-keys -t "$target" "$*"
