name: Test Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-scripts:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install tmux on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/\
                          Homebrew/install/HEAD/install.sh)"
          fi
          brew install tmux fd fzf

      - name: Install tmux on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux
          sudo apt-get install -y fd-find
          sudo apt-get install -y fzf

      - name: Set up tmux environment
        run: |
          tmux new-session -d -s mysession
          tmux new-window -t mysession:1 -n mywindow

      - name: Test aactivator.py
        run: |
          python aactivator.py

      # - name: Test tmux_sessionizer
      #   run: |
      #     chmod +x tmux_sessionizer
      #     ./tmux_sessionizer
      #
      # - name: Test tmux_windownizer
      #   run: |
      #     chmod +x tmux_windownizer
      #     ./tmux_windownizer

      - name: Test setup_dev_environment.sh
        run: |
          chmod +x setup_dev_env
          ./setup_dev_env
