name: Test Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-scripts:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Test aactivator.py
        run: |
          chmod +x aactivator.py
          ./aactivator.py --version

      - name: Test tmux_sessionizer
        run: |
          chmod +x tmux_sessionizer
          ./tmux_sessionizer --version

      - name: Test tmux_windownizer
        run: |
          chmod +x tmux_windownizer
          ./tmux_windownizer --version

      - name: Test update_brew_lists
        run: |
          chmod +x update_brew_lists
          ./update_brew_lists --version

      - name: Test setup_dev_environment.sh
        run: |
          chmod +x setup_dev_environment.sh
          ./setup_dev_environment.sh --version
